version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/PalaverliteBackend
hooks:
  BeforeInstall:
    - location: scripts/stop_server.sh
      timeout: 1000
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 1000
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 1000
